<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-DLOSR1I" failures="1" tests="3" name="Test" time="16.018" errors="0" timestamp="2024-11-02T11:35:47 IST">
  <testcase classname="testngpractice.MyTestReporting" name="testLogo" time="0.085"/>
  <testcase classname="testngpractice.MyTestReporting" name="testAppUrl" time="0.022">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/log] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/log] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at testngpractice.MyTestReporting.testAppUrl(MyTestReporting.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testAppUrl -->
  <testcase classname="testngpractice.MyTestReporting" name="testTitle" time="0.001">
    <skipped/>
  </testcase> <!-- testTitle -->
</testsuite> <!-- Test -->
